definitions:
  main.user:
    properties:
      ID:
        type: string
      Name:
        type: string
    type: object
info:
  contact: {}
paths:
  /users:
    get:
      description: Retorna a lista de usuários
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/main.user'
            type: array
      summary: Lista todos os usuários
      tags:
      - users
  /users/post:
    post:
      description: Adiciona um novo usuário ao json
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            items:
              $ref: '#/definitions/main.user'
            type: array
      summary: Adicionar um novo usuário
      tags:
      - users
swagger: "2.0"
