basePath: /api/v1
definitions:
  user.User:
    properties:
      createdAt:
        type: string
      id:
        type: integer
      name:
        type: string
      updatedAt:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: API de exemplo
  title: REST API go
  version: "2.0"
paths:
  /:
    get:
      description: Retorna a lista de usuários
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/user.User'
            type: array
      security:
      - BearerAuth: []
      summary: Lista todos os usuários
      tags:
      - users
  /:ID:
    get:
      description: Retorna o usuário filtrado por ID
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/user.User'
            type: array
      security:
      - BearerAuth: []
      summary: Lista o usuário com o ID desejado
      tags:
      - users
  /delete/:ID:
    delete:
      description: Remove o usuário com o determinado id no json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/user.User'
            type: array
      security:
      - BearerAuth: []
      summary: Remover usuário por id
      tags:
      - users
  /login:
    post:
      description: Única rota pública para fazer login e receber o token
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            items:
              $ref: '#/definitions/user.User'
            type: array
      security:
      - BearerAuth: []
      summary: Rota para logar na API
      tags:
      - login
  /post:
    post:
      description: Adiciona um novo usuário ao json
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            items:
              $ref: '#/definitions/user.User'
            type: array
      security:
      - BearerAuth: []
      summary: Adicionar um novo usuário
      tags:
      - users
  /update:
    patch:
      description: Muda o nome do usuário definido por url, com id e name
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/user.User'
            type: array
      security:
      - BearerAuth: []
      summary: Faz o update do user
      tags:
      - users
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
